# Generated by Django 4.2.4 on 2023-08-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Receipts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('body', models.TextField(blank=True)),
                ('ingredient', models.TextField(blank=True)),
                ('image', models.ImageField(default=None, upload_to='images/')),
                ('tags', models.ManyToManyField(to='api.tag')),
            ],
            options={
                'ordering': ['title', 'body', 'ingredient', 'image'],
            },
        ),
    ]
